version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: postgres-spring
    ports:
      - "5499:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sistema_organizador
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
