alter table im_products
add column brand varchar(255),
add column model varchar (255),
add column version varchar(50),
add column id_supplier INT,
add column id_second_supplier INT,
add column color varchar (255),
add column dimensions varchar (100),
add column gross_weight decimal(25, 2),
add column net_weight decimal(25, 2),
add column product_datails text,
add column unit_of_measurement varchar(4),
add column unit_of_measurement_description varchar(200),
add column unit_price_of_last_purchase decimal (25, 2),
add column average_unit_price decimal (25, 2),
add column created_by INT,
add column updated_by INT,
add column created_at timestamp default current_timestamp,
add column updated_at timestamp;