create table im_purchase_order (
	id serial primary key,
	date_of_issue timestamp default current_timestamp,
	order_status status_purchase_order,
	id_project INT,
	id_company INT not null,
	id_paymant_conditions INT not null,
	id_delivery_conditions INT not null,
	total_ipi decimal(15, 2),
	total_icms decimal(15, 2),
	subtotal decimal (25, 2),
	discount_value decimal(25, 2),
	discount_description text,
	total_net_value decimal(30, 2) not null,
	general_observations varchar(255),
	business_observations varchar(255),
	supplier_business varchar(255),
	created_by INT not null,
	updated_by INT,
	approvet_by INT not null,
	created_at timestamp default current_timestamp,
	updated_at timestamp,
	approvet_at timestamp
);