ALTER TABLE im_warehouses
ADD COLUMN isActive BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE im_locations
ADD COLUMN isActive BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE im_stock
ADD COLUMN isActive BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE im_positions
ADD COLUMN isActive BOOLEAN NOT NULL DEFAULT TRUE;